name: Deploy to EC2 (nohup)

on:
  push:
    branches: [ "main" ]   # main 브랜치에 push 시 실행

jobs:
  deploy:
    runs-on: self-hosted   # EC2에 설치한 GitHub Actions Runner에서 실행

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build JAR
        run: ./gradlew clean build -x test

      - name: Stop old process (nohup or Docker)
        run: |
          pkill -f 'java -jar' || true

      - name: Run new process (nohup)
        run: |
          nohup java -jar build/libs/*.jar \
            --spring.profiles.active=dev \
            > app.log 2>&1 &