export default {
  namespaced: true,
  state: {
    oralCheckType: [
      { text: '건강', value: 'HEALTHY' },
      { text: '양호', value: 'GOOD' },
      { text: '주의', value: 'ATTENTION' },
      { text: '위험', value: 'DANGER' },
    ],
    oralStatus: [
      { text: '양치 관리형', value: 'A', color: '#F3B6B5' },
      { text: '충치 관리형', value: 'B', color: '#FCEEE7' },
      { text: '잇몸 관리형', value: 'C', color: '#FAE7E6' },
      { text: '시린니 관리형', value: 'D', color: '#E4D5D2' },
      { text: '보철 관리형', value: 'E', color: '#E3D2DB' },
      { text: '교정 관리형', value: 'F', color: '#FAE7FD' },
      { text: '일반 관리형', value: 'G', color: '#E6E8FD' },
      { text: '구취 관리형', value: 'H', color: '#E9F4FE' },
      { text: '영유아형', value: 'I', color: '#DAFFFD' },
      { text: '키즈형', value: 'J', color: '#C3DDE4' },
      { text: '시니어형', value: 'K', color: '#C3CCE3' },
    ],
    joinStatus: [
      { text: '가입', value: 'Y' },
      { text: '미가입', value: 'N' },
    ],
    genderStatus: [
      { text: '남자', value: 'M' },
      { text: '여자', value: 'W' },
    ],
    verifyStatus: [
      { text: '회원', value: 'Y' },
      { text: '비회원', value: 'N' },
    ],
    cellRangeItems: [
      { text: '10개씩 보기', value: 10 },
      { text: '50개씩 보기', value: 50 },
      { text: '100개씩 보기', value: 100 },
    ],
    userListHeaders: [
      { text: '번호', align: 'start', value: 'num' },
      { text: '아이디', value: 'userLoginIdentifier' },
      { text: '닉네임', value: 'userName' },
      { text: '성별', value: 'userGender' },
      { text: '연락처', value: 'patientPhoneNumber' },
      { text: '문진표 유형', value: 'oralStatus' },
      { text: '문진표 검사일', value: 'questionnaireDate' },
      { text: '구강상태', value: 'oralCheckResultTotalType' },
      { text: '구강 촬영일', value: 'oralCheckDate' },
      { text: '인증여부', value: 'isVerify' },
      { text: '인증', value: 'tools', sortable: false },
      { text: '수정하기', value: 'tools', sortable: false },
      { text: '삭제하기', value: 'tools', sortable: false },
    ],
    patientListHeaders: [
      { text: '번호', align: 'start', value: 'num' },
      { text: '이름', value: 'patientName' },
      { text: '연락처', value: 'patientPhoneNumber' },
      { text: '등록일', value: 'created' },
      { text: '가입 여부', value: 'isUser' },
      { text: '삭제하기', value: 'tools', sortable: false },
    ],
    adminListHeaders: [
      { text: '번호', align: 'start', value: 'num' },
      { text: '관리자', value: 'name' },
      { text: '연락처', value: 'tel' },
      { text: '아이디', value: 'loginid' },
      { text: '가입일', value: 'created' },
      { text: '', value: 'tools', sortable: false },
    ],
    statisticsRankListHeaders: [
      { text: '우수 양치습관 순위', value: 'index', sortable: false },
      { text: '부대', value: 'corName', sortable: false },
      { text: '이름', value: 'name', sortable: false },
      { text: '구강촬영횟수', value: 'count', sortable: false },
      { text: '평균 구강상태', value: 'state', sortable: false },
      { text: '지역 내 구강건강 최고 순위 (플라그 체크)', value: 'oralConditionRank', sortable: false },
      { text: '최근 구강촬영일시)', value: 'latestDate', sortable: false },
    ],
    healthStatus: {
      HEALTHY: {
        text: '건강',
        paragraph: '건강입니다',
        value: 4,
        color: '#A9D0FC',
        icon: 'health',
        description: '양치질을 전문가<br/>수준으로 잘하셨어요!',
        infoText: '화살표 방향이 바뀌지 않도록<br/>양치를 계속 잘해주세요.',
      },
      GOOD: {
        text: '양호',
        paragraph: '양호입니다',
        value: 3,
        color: '#D6FCCF',
        icon: 'good',
        description: '정확한 양치 습관을<br/>가지고 있어요!',
        infoText: '화살표가 위로 향할 수 있도록<br/>조금만 힘내주세요.',
      },
      ATTENTION: {
        text: '주의',
        paragraph: '주의입니다',
        value: 2,
        color: '#FFFFC3',
        icon: 'attention',
        description: '올바른 양치질 필요!<br/>진돗개 둘 발령',
        infoText: '건강한 구강상태로<br/>돌아올 수 있도록 더 노력해 보세요.',
      },
      DANGER: {
        text: '위험',
        paragraph: '위험입니다',
        value: 1,
        color: '#FDC9C4',
        icon: 'danger',
        description: '치아에 적군이 득실!<br/>진돗개 하나 발령',
        infoText: '구강상태가 하향세입니다.<br/>양치에 더욱 신경써주세요.',
      },
    },
  },
};
