spring:
  application:
    name: dentix-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: "optional:configserver:https://config.kai-i.com/"
  cloud:
    config:
      name: dentix
      profile: ${SPRING_PROFILES_ACTIVE}
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}

encrypt:
  key: ${CONFIG_SERVER_ENCRYPT_KEY}

---
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  forward-headers-strategy: native
  servlet:
    encoding:
      charset: UTF-8
      force: true